### PR TITLE
Update color in color cycle

### PR DESCRIPTION
**Pull request by cadenmyers13**
@sbillinge Replaced one of the maroon colors with a pink color. the HEX is #F1BAF2.

### CODE REVIEW

**Comment by sbillinge** [comment]
fantastic!  Please can you generate the new figure for the updated documentation and I will take a look.

**Comment by sbillinge** [comment]
please paste it in here.

**Comment by cadenmyers13** [comment]
Figure_1

@sbillinge I ended up changing a few colors because it felt like it was clashing haha. Let me know if I should change any other colors.

**Comment by sbillinge** [comment]
let's revert.  I don't like these colors.  They are quite different and heading in the wrong direction imho.

If you can find the right color to replace that one that is too close, please try again and find one that fits into the palette.

Alternatively, we can may be able to figure out how to have more than one palette available and make it user-selected, though I am not sure how to do that.

**Comment by cadenmyers13** [comment]
Figure_1
@sbillinge Okay, heres an updated version. These colors are more similar to the original

**Comment by sbillinge** [comment]
That looks better.  A comparison would be most helpful.

**Comment by sbillinge** [comment]
that looks really good.  Thanks Caden!

**Comment by sbillinge** [comment]
I forgot to ask to add a news item.  Please could you make that on a new PR, or add it to another PR that implements the color list or sthg, if someone is working on that?

**Pull request merged**
