### PR TITLE
Instruct to install Python 3.12 for conda environment in README

### PR DESCRIPTION
**Pull request by bobleesj**
To prevent from conda-forge to automatically install Python 3.13 which causes the following issue: https://github.com/Billingegroup/bg-mpl-stylesheets/issues/75

### CODE REVIEW

**Comment by bobleesj** [comment]
Local test:

```
conda create -n bg-mpl-stylesheets_env bg-mpl-stylesheets python=3.12
conda activate bg-mpl-stylesheets_env
conda install --file requirements/examples.txt
python example/plot.py
```
Screenshot 2024-10-24 at 8 07 22 AM

**Comment by bobleesj** [comment]
@sbillinge ready for review - will create an issue to remove Python 3.12 pinning when we migrate to support Python 3.13

**Comment by sbillinge** [comment]
please see my comment on #75.  I suggest we just push out the 3.13 fix....

**Comment by bobleesj** [comment]
Closing - going with 3.13 instead of pinning 3.12.

**Pull request closed without merging**
