### PR TITLE
Applying cookiecutter

### PR DESCRIPTION
**Pull request by cadenmyers13**

### CODE REVIEW

**Review by sbillinge — COMMENTED** [review]
looks good, thanks so much!

some things I see:

1. delete LICENSE.txt (its replaced with the LICENSE.rst)
2. please merge the old README.md into the README.rst and delete the old README.md
3. check through the README for broken links and missing things
4. I think the `bg_mpl_stylesheet/__init__.py` needs to be updated.  We are not using hard-coded version numbers any more.  It should have been replaced with a cookiecutter generated version.
5. if possible, build the docs and see what they look like....
6. delet requirements/README.txt when you have read and done everything
7. delete setup.py
8. fix init in src (see how it is handled in diffpy.pdfmorph for example)
9. remove bg_mpl_stylesheet tree after checking it has all been moved to `src/bg-mpl-stylesheet` tree
10. remove everything except `bg-mpl-stylesheets` and `__init__.py` from `src`

Make sure to test things after all this work.  Make an env of a program that imports the stylesheet currently and verify it works (I think pdfmorph does?) then make a new env that installs the stylesheet from your new branch and make sure nothing breaks, something like that.

**Comment by cadenmyers13** [comment]
Messed up in editing the README.rst... working on fixing things

**Comment by cadenmyers13** [comment]
> looks good, thanks so much!
> 
> some things I see:
> 
> 1. delete LICENSE.txt (its replaced with the LICENSE.rst)
> 2. please merge the old README.md into the README.rst and delete the old README.md
> 3. check through the README for broken links and missing things
> 4. I think the `bg_mpl_stylesheet/__init__.py` needs to be updated.  We are not using hard-coded version numbers any more.  It should have been replaced with a cookiecutter generated version.
> 5. if possible, build the docs and see what they look like....
> 6. delet requirements/README.txt when you have read and done everything
> 7. delete setup.py
> 8. fix init in src (see how it is handled in diffpy.pdfmorph for example)
> 9. remove bg_mpl_stylesheet tree after checking it has all been moved to `src/bg-mpl-stylesheet` tree
> 10. remove everything except `bg-mpl-stylesheets` and `__init__.py` from `src`
> 
> Make sure to test things after all this work. Make an env of a program that imports the stylesheet currently and verify it works (I think pdfmorph does?) then make a new env that installs the stylesheet from your new branch and make sure nothing breaks, something like that.

Are LICENSE.txt and README.md not removed in this? Same with setup.py. When i look in 'files changed' it looks likes they've been deleted.

**Comment by cadenmyers13** [comment]
@sbillinge In the "Support and Contribute" section of the README, the cookiecutter put information about diffpy. Since this not a diffpy package I assume we don't want this. Is there something you'd like me replace this with?

**Comment by cadenmyers13** [comment]
I made the __init__.py files dynamic by coping the format in `src/bg-mpl-stylesheets/__init__.py`.

**Comment by cadenmyers13** [comment]
@sbillinge Okay, I made all the suggested edits. I ran `pip install .` and it install successfully. The only things I feel shaky on are the __init__.py files i edited in the above commits. Also, check the above comment i tagged you in regarding the README.rst. Let me know if anything else needs to be done!

**Review by sbillinge — COMMENTED** [review]
Thanks @cadenmyers13 this is great.   Here are my comments:
1. we need a news that describes the cookiecuttering
2. pip.txt should be empty
4. remove bg-mpl-stylesheets from run.txt (the package is not a dependency of itself)
5. we might want to think about how we handle dependencies in general.  No dependencies are required to use hte package so I htink run.txt and pip.txt should both be empty.  The other requirements are only needed to run the examples.  Let's put those requirements into test.txt and in the instructions in the README.rst and docs have people install `requirements/test.txt` before running the examples.  In this way, when people grab this into their code as a dependency it doesn't bring along all those packages.
6. delete `src/__init__.py`
7. I see the readme.md and setup.py gone now.  Not sure why I thought they weren't deltetd before...sorry about that.
8. I still see "LONGER DESCRIPTION HERE" in the readme.rst.  Please replace with a slightly expanded description of what the package contains and how it is used.
9. The readme needs to be tweaked too to better reflect how the package is used.  The only reason to build an env is to run the examples, but this is really not necessary.  Normally the package will just be imported into other packages as a dependency.  Please could you have a crack at writing that?
10. I see a Makefile in `doc/` and `doc/source/`.  We only need the latter.  Please also delete the make.bat from `doc/`
11. I don't think we have any tests so we can remove the conftest.py, run.py and debug.py from the tests directory.  I would leave the directory and the init fil there though, in case we write tests later.

The basic guide to all these is that the structure should look like diffpy.utils or diffpy.pdfmorph, so if you are not sure, cross-check with them.  The cookiecutter is designed to help in this process, but at the end of the day we are hoping that you can take charge and double-check everything.  Please use this paradigm to synchronize the __init__.py issues.  I still see that it is not quite the same.

OK, I think that's it.  Nearly there.

**Comment by sbillinge** [comment]
Please don't force-push.  I don't really want to merge anything with a force-push, it is too dangerous.  Why are you force-pushing?

**Comment by sbillinge** [comment]
@cadenmyers13 this PR is getting a bit messy.  I wonder if we should make use of what we learned in the process, and just start over.... I think it could go quickly and we would be more satisfied with the outcome.   Perhaps we can do a PR that does the pre-commit things before the cookiecutter, following the new instructions?

**Comment by cadenmyers13** [comment]
> @cadenmyers13 this PR is getting a bit messy. I wonder if we should make use of what we learned in the process, and just start over.... I think it could go quickly and we would be more satisfied with the outcome. Perhaps we can do a PR that does the pre-commit things before the cookiecutter, following the new instructions?

I agree especially since I've done it once by myself. I will start fresh.

**Pull request closed without merging**
